org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=birdzoom
mod.name=Bird Zoom
mod.group=bluebird
mod.version=1.1
mod.version_prefix=
mod.version_suffix=
mod.authors=BluebirdDevs
mod.contributors=
mod.license=ARR
mod.description=A simple zoom mod that fixes common issues found in others
mod.sources_url=https://github.com/BluebirdDevs/BirdZoom
mod.homepage_url=https://modrinth.com/project/FQUBFXkG
mod.issues_url=https://github.com/BluebirdDevs/BirdZoom/issues

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

# Publishing
publish.dryrun=false

publish.modrinth.id=FQUBFXkG
publish.curseforge.id=1710553

publish.modrinth=false
publish.curseforge=false

publish.release.fabric=stable
publish.release.neoforge=stable
publish.release.forge=stable
